
#griffin_GC_frequency.snakefile
#Anna-Lisa Doebley
#Template made 2021-04-06
#Ha Lab
#Fred Hutchinson Cancer Research Center

mapable_regions: #The genome GC frequencies
  ../downloads/genome/repeat_masker.mapable.k50.Umap.hg38.bedGraph

reference_genome: 
  /fh/fast/ha_g/grp/reference/GRCh38/GRCh38.fa

chrom_sizes: 
  /fh/fast/ha_g/grp/reference/GRCh38/hg38.standard.chrom.sizes

out_dir: 
  results

size_range: [1,500]
