#griffin_GC_correction.snakefile
#Anna-Lisa Doebley
#Template made 2021-04-06
#Ha Lab
#Fred Hutchinson Cancer Research Center

griffin_scripts_dir: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/Griffin/scripts

#################
#mappability bias params##
#################
# #SELECT CORRECT REFERENCE GENOME
# #reference genome for alignment, with index files in same folder as .fa file
reference_genome: /fh/fast/ha_g/grp/reference/GRCh38/GRCh38.fa

#chrom sizes for the selected reference genome
chrom_sizes: /fh/fast/ha_g/grp/reference/GRCh38/hg38.standard.chrom.sizes #don't change this

#file containing mappability value for each bp in the genome 
mappability_bw: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/k100.Umap.MultiTrackMappability.hg38.bw

#bed file containing regions to exclude
encode_exclude: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/encode_unified_GRCh38_exclusion_list.bed
centromeres: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_centromeres.bed
gaps: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_gaps.bed
patches: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_fix_patches.bed
alternative_haplotypes: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_alternative_haplotypes.bed

#where the GC bias output will go
out_dir: results

#minimum mapping quality to keep a read
map_quality: 20


#################
#GC bias params##
#################
mappable_regions: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/k100_minus_exclusion_lists.mappable_regions.hg38.bed

#folder with the gc frequencies for all fragment sizes in the mapable regions (must match the mapable_regions)
#For typical hg38 WGS the correct path is below
genome_GC_frequency: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/Griffin/snakemakes/griffin_genome_GC_frequency/results

GC_bias_size_range: 15 500
